// +build ignore

package main

import (
	"bytes"
	"go/format"
	"io/ioutil"
	"strconv"
	"text/template"
	"unicode"

	"github.com/jasonmoo/usgs/earthquake"
)

var (
	funcMap = template.FuncMap{
		"slug": slug,
	}
	slugs = make(map[string]int)
)

func slug(s string) string {

	rs := []rune(s)

	for i, r := range rs {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			rs[i] = '_'
		}
	}
	for len(rs) > 0 {
		if rs[0] == '_' {
			rs = rs[1:]
		} else {
			break
		}
	}

	rs[0] = unicode.ToUpper(rs[0])

	var usi int
	for i := 1; i < len(rs); {
		switch {
		case rs[i] == '_' && usi == 0:
			usi = i
			i++
		case rs[i] != '_' && usi > 0:
			rs[i] = unicode.ToUpper(rs[i])
			rs = append(rs[:usi], rs[i:]...)
			usi = 0
		default:
			i++
		}
	}

	s = string(rs)

	n, exists := slugs[s]
	slugs[s]++
	if exists {
		s += strconv.Itoa(n)
	}

	return s

}

const constantsTemplate = `package earthquake

// This file is generated by generate_constants.go
// DO NOT EDIT

const (
	{{ range $name := .Catalogs }}{{ printf "Catalog_%s" $name | slug }} Catalog = {{ printf "%q\n" $name }}{{ end }}
	{{ range $name := .Contributors }}{{ printf "Contributor_%s" $name | slug }} Contributor = {{ printf "%q\n" $name }}{{ end }}
	{{ range $name := .EventTypes }}{{ printf "EventType_%s" $name | slug }} EventType = {{ printf "%q\n" $name }}{{ end }}
	{{ range $name := .MagnitudeTypes }}{{ printf "MagnitudeType_%s" $name | slug }} MagnitudeType = {{ printf "%q\n" $name }}{{ end }}
	{{ range $name := .ProductTypes }}{{ printf "ProductType_%s" $name | slug }} ProductType = {{ printf "%q\n" $name }}{{ end }}
)
`

func main() {

	resp, err := earthquake.NewClient().GetApplicationInfo()
	if err != nil {
		panic(err)
	}

	var buf bytes.Buffer
	temp := template.Must(template.New("").Funcs(funcMap).Parse(constantsTemplate))
	if err := temp.Execute(&buf, resp); err != nil {
		panic(err)
	}

	data, err := format.Source(buf.Bytes())
	if err != nil {
		panic(err)
	}

	if err := ioutil.WriteFile("constants.go", data, 0600); err != nil {
		panic(err)
	}

}
